#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircuitCourtLookupMvvm.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LettersConsolidated.Models.DatabaseContexts.PacerSentAddressesDbContext")]
	public partial class PacerSentLettersDbContextLinqToSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAttorneyInfoPacerSentAddress(AttorneyInfoPacerSentAddress instance);
    partial void UpdateAttorneyInfoPacerSentAddress(AttorneyInfoPacerSentAddress instance);
    partial void DeleteAttorneyInfoPacerSentAddress(AttorneyInfoPacerSentAddress instance);
    #endregion
		
		public PacerSentLettersDbContextLinqToSqlDataContext() : 
				base(global::CircuitCourtLookupMvvm.Properties.Settings.Default.LettersConsolidated_Models_DatabaseContexts_PacerSentAddressesDbContextConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PacerSentLettersDbContextLinqToSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PacerSentLettersDbContextLinqToSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PacerSentLettersDbContextLinqToSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PacerSentLettersDbContextLinqToSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AttorneyInfoPacerSentAddress> AttorneyInfoPacerSentAddresses
		{
			get
			{
				return this.GetTable<AttorneyInfoPacerSentAddress>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AttorneyInfoPacerSentAddresses")]
	public partial class AttorneyInfoPacerSentAddress : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private bool _LetterReturned;
		
		private string _Filename;
		
		private System.Nullable<System.DateTime> _DateProcessed;
		
		private string _FullName;
		
		private string _CombinedAddress;
		
		private string _Circuit;
		
		private string _ShortTitle;
		
		private string _Caption;
		
		private string _Email;
		
		private string _Phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnLetterReturnedChanging(bool value);
    partial void OnLetterReturnedChanged();
    partial void OnFilenameChanging(string value);
    partial void OnFilenameChanged();
    partial void OnDateProcessedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateProcessedChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnCombinedAddressChanging(string value);
    partial void OnCombinedAddressChanged();
    partial void OnCircuitChanging(string value);
    partial void OnCircuitChanged();
    partial void OnShortTitleChanging(string value);
    partial void OnShortTitleChanged();
    partial void OnCaptionChanging(string value);
    partial void OnCaptionChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    #endregion
		
		public AttorneyInfoPacerSentAddress()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterReturned", DbType="Bit NOT NULL")]
		public bool LetterReturned
		{
			get
			{
				return this._LetterReturned;
			}
			set
			{
				if ((this._LetterReturned != value))
				{
					this.OnLetterReturnedChanging(value);
					this.SendPropertyChanging();
					this._LetterReturned = value;
					this.SendPropertyChanged("LetterReturned");
					this.OnLetterReturnedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(MAX)")]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this.OnFilenameChanging(value);
					this.SendPropertyChanging();
					this._Filename = value;
					this.SendPropertyChanged("Filename");
					this.OnFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateProcessed", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateProcessed
		{
			get
			{
				return this._DateProcessed;
			}
			set
			{
				if ((this._DateProcessed != value))
				{
					this.OnDateProcessedChanging(value);
					this.SendPropertyChanging();
					this._DateProcessed = value;
					this.SendPropertyChanged("DateProcessed");
					this.OnDateProcessedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(MAX)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CombinedAddress", DbType="NVarChar(MAX)")]
		public string CombinedAddress
		{
			get
			{
				return this._CombinedAddress;
			}
			set
			{
				if ((this._CombinedAddress != value))
				{
					this.OnCombinedAddressChanging(value);
					this.SendPropertyChanging();
					this._CombinedAddress = value;
					this.SendPropertyChanged("CombinedAddress");
					this.OnCombinedAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Circuit", DbType="NVarChar(MAX)")]
		public string Circuit
		{
			get
			{
				return this._Circuit;
			}
			set
			{
				if ((this._Circuit != value))
				{
					this.OnCircuitChanging(value);
					this.SendPropertyChanging();
					this._Circuit = value;
					this.SendPropertyChanged("Circuit");
					this.OnCircuitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortTitle", DbType="NVarChar(MAX)")]
		public string ShortTitle
		{
			get
			{
				return this._ShortTitle;
			}
			set
			{
				if ((this._ShortTitle != value))
				{
					this.OnShortTitleChanging(value);
					this.SendPropertyChanging();
					this._ShortTitle = value;
					this.SendPropertyChanged("ShortTitle");
					this.OnShortTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Caption", DbType="NVarChar(MAX)")]
		public string Caption
		{
			get
			{
				return this._Caption;
			}
			set
			{
				if ((this._Caption != value))
				{
					this.OnCaptionChanging(value);
					this.SendPropertyChanging();
					this._Caption = value;
					this.SendPropertyChanged("Caption");
					this.OnCaptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(MAX)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(MAX)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
