//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CircuitCourtLookupMvvm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CLB15020\\SQLEXPRESS;Initial Catalog=LettersConsolidated.Models.PacerS" +
            "entAddressesDbContext;Integrated Security=True;Encrypt=False;TrustServerCertific" +
            "ate=True")]
        public string LettersConsolidated_Models_PacerSentAddressesDbContextConnectionString {
            get {
                return ((string)(this["LettersConsolidated_Models_PacerSentAddressesDbContextConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=CLB15020\\SQLEXPRESS;Initial Catalog=LettersConsolidated.Models.Databa" +
            "seContexts.PacerSentAddressesDbContext;Integrated Security=True;Encrypt=False;Tr" +
            "ustServerCertificate=True")]
        public string LettersConsolidated_Models_DatabaseContexts_PacerSentAddressesDbContextConnectionString {
            get {
                return ((string)(this["LettersConsolidated_Models_DatabaseContexts_PacerSentAddressesDbContextConnection" +
                    "String"]));
            }
        }
    }
}
